<?php

/**
 * @file
 * Apple News module file.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function applenews_entity_insert(EntityInterface $entity) {
  try{
    /** @var \Drupal\applenews\ApplenewsManager $manager */
    $manager = \Drupal::service('applenews.manager');
    $response = $manager->postArticle($entity);

  }
  catch (\Exception $e) {
    \Drupal::logger('applenews')->error(t('Error posting  to Apple News'));
  }

}
